# Generated by Django 5.2.12 on 2026-05-19 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerotp_customer_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerotp',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customerotp',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
